"use strict";
(() => {
  const title='三大重點與年度執行規劃';
  const axes=[
    {id:'culture',title:'建立文化',focus:'家人 → 股東',detail:'保留情誼，建立共同經營的承諾與商務行動。'},
    {id:'accountability',title:'當責',focus:'會員當責・核心當責・對生意當責',detail:'會員、核心與商務成果，分別討論如何承擔與落實。'},
    {id:'pt',title:'特色型分會',focus:'至少產出 1 條 PT，目標 2 條',detail:'討論本屆 PT 的發展方向與每月執行工作。'}
  ];
  const months=Array.from({length:12},(_,i)=>i<3?`2026-${i+10}`:`2027-${String(i-2).padStart(2,'0')}`);
  const quarters=Array.from({length:4},(_,i)=>({id:'q'+(i+1),label:'Q'+(i+1),period:i===0?'2026/10–12':`2027/${i*3-2}–${i*3}`,months:months.slice(i*3,i*3+3)}));
  const empty=()=>({version:1,termId:'term-11',axes:axes.map(a=>({...a,quarters:quarters.map(q=>({id:q.id,direction:'',months:q.months.map(month=>({month,action:''}))}))}))});
  function validate(plan){
    const fail=()=>{throw Error('年度規劃格式不符，請核對三大主軸、季度與月份。');};
    if(!plan||plan.version!==1||plan.termId!=='term-11'||!Array.isArray(plan.axes)||plan.axes.length!==3)fail();
    plan.axes.forEach((a,i)=>{if(!a||a.id!==axes[i].id||typeof a.title!=='string'||!a.title.trim()||a.title.length>160||typeof a.focus!=='string'||a.focus.length>500||typeof a.detail!=='string'||a.detail.length>1000||!Array.isArray(a.quarters)||a.quarters.length!==4)fail();
      a.quarters.forEach((q,j)=>{if(!q||q.id!==quarters[j].id||typeof q.direction!=='string'||q.direction.length>4000||!Array.isArray(q.months)||q.months.length!==3)fail();q.months.forEach((m,k)=>{if(!m||m.month!==quarters[j].months[k]||typeof m.action!=='string'||m.action.length>4000)fail();});});
    });
  }
  const hasContent=plan=>plan?.axes.some(a=>a.quarters.some(q=>q.direction.trim()||q.months.some(m=>m.action.trim())));
  const selection=(plan,s={})=>({axis:plan.axes.some(a=>a.id===s.axis)?s.axis:plan.axes[0].id,quarter:Number.isInteger(s.quarter)&&s.quarter>=0&&s.quarter<4?s.quarter:0});
  const short=(text,n=48)=>{const s=text.trim().split('\n').filter(Boolean).join('；');return s.length>n?s.slice(0,n)+'…':s;};
  function chart(plan,s,E){s=selection(plan,s);return `<div class="strategy-scroll" tabindex="0" role="region" aria-label="年度甘特圖，可左右捲動"><div class="strategy-gantt"><div class="sg-quarter-head"><div class="sg-sticky">第 11 屆 · 年度規劃</div>${quarters.map(q=>`<div class="sg-quarter-label"><strong>${q.label}</strong> ${q.period}</div>`).join('')}</div><div class="sg-month-head"><div class="sg-sticky">主軸 → 季度 → 月份</div>${months.map(m=>`<span>${Number(m.slice(5))}月</span>`).join('')}</div>${plan.axes.map((a,ai)=>`<div class="sg-axis sg-${a.id}"><div class="sg-row sg-main"><div class="sg-sticky sg-axis-name"><span>0${ai+1}</span><strong>${E(a.title)}</strong></div><div class="sg-year-bar"><span>${E(a.focus)}</span><small>年度主軸</small></div></div><div class="sg-row sg-quarter-row"><div class="sg-sticky sg-level">↳ 季度方向</div>${a.quarters.map((q,qi)=>`<button type="button" data-mw="strategy-select" data-axis="${a.id}" data-quarter="${qi}" class="sg-quarter ${q.direction.trim()?'is-filled':''} ${s.axis===a.id&&s.quarter===qi?'is-selected':''}" aria-label="${E(a.title)} ${quarters[qi].label} 季度方向" aria-pressed="${s.axis===a.id&&s.quarter===qi}"><small>${quarters[qi].label}</small><span>${E(short(q.direction)||'＋ 討論季度方向')}</span></button>`).join('')}</div><div class="sg-row sg-action-row"><div class="sg-sticky sg-level">↳ 每月工作</div>${a.quarters.flatMap((q,qi)=>q.months.map((m,mi)=>`<button type="button" data-mw="strategy-select" data-axis="${a.id}" data-quarter="${qi}" data-month="${mi}" class="sg-month ${m.action.trim()?'is-filled':''}" aria-label="${E(a.title)} ${m.month} 每月工作" title="${E(m.action||'尚未設定工作')}">${m.action.trim()?`<span>${E(short(m.action,16))}</span>`:'<span class="sg-empty">＋</span>'}</button>`)).join('')}</div></div>`).join('')}</div></div>`;}
  function editor(plan,s,E){s=selection(plan,s);const a=plan.axes.find(a=>a.id===s.axis),q=a.quarters[s.quarter],period=quarters[s.quarter];return `<div class="strategy-editor sg-${a.id}"><div class="strategy-editor-head"><div><small>${E(a.title)} · ${period.period}</small><h4>${period.label} 執行方向與每月工作</h4></div><div class="strategy-quarter-nav">${quarters.map((v,i)=>`<button type="button" data-mw="strategy-select" data-axis="${a.id}" data-quarter="${i}" aria-pressed="${i===s.quarter}" class="${i===s.quarter?'active':''}">${v.label}</button>`).join('')}</div></div><p class="strategy-focus">${E(a.focus)}<span>${E(a.detail)}</span></p><label>季度執行方向<textarea data-strategy-field="direction" data-axis="${a.id}" data-quarter="${s.quarter}" rows="2" maxlength="4000" placeholder="這一季要往什麼方向推進？">${E(q.direction)}</textarea></label><div class="strategy-month-editors">${q.months.map((m,mi)=>`<label>${Number(m.month.slice(5))} 月工作<textarea data-strategy-field="action" data-axis="${a.id}" data-quarter="${s.quarter}" data-month="${mi}" rows="3" maxlength="4000" placeholder="這個月要做什麼？可分行記錄。">${E(m.action)}</textarea></label>`).join('')}</div></div>`;}
  function html(plan,s,E){return `<div class="strategy-plan"><div class="strategy-intro"><span>2026/10 — 2027/9</span><small>點選季度或月份，往下填寫執行方向。</small></div><div data-strategy-chart>${chart(plan,s,E)}</div><div class="strategy-legend"><span><i></i>已填規劃</span><span>＋ 待討論</span><span>色條表示年度主軸，並非完成進度</span></div><div data-strategy-editor>${editor(plan,s,E)}</div></div>`;}
  function summary(plan,E){return `<div class="mw-snapshot-section"><strong>${title} · 2026/10—2027/9</strong>${plan.axes.map(a=>`<h4>${E(a.title)} · ${E(a.focus)}</h4>${a.quarters.map((q,i)=>`<p><b>${quarters[i].label}（${quarters[i].period}）</b> ${E(q.direction||'季度方向待討論')}</p>${q.months.filter(m=>m.action.trim()).map(m=>`<p>${E(m.month)}：${E(m.action)}</p>`).join('')}`).join('')}`).join('')}</div>`;}
  window.ChairStrategy=Object.freeze({title,axes,months,quarters,empty,validate,hasContent,selection,chart,editor,html,summary});
})();
