"use strict";
(() => {
  window.ChairTermKpiUI={create({getData,commit,identity,escape:E,toast}){
    const M=ChairTermKpi,panel=document.getElementById('termKpiPanel'),dialog=document.getElementById('termKpiEditor');let state=null;
    const stamp=at=>new Date(at).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
    const metrics=(values,cls='kpi-grid')=>`<dl class="${cls}">${M.fields.map(f=>`<div data-kpi-metric="${f.id}"><dt>${E(f.label)}</dt><dd><strong>${M.display(values[f.id])}</strong><span>${f.unit}</span></dd></div>`).join('')}</dl>`;
    const groups=[['分會規模',['members','visitors','greenMembers']],['商務活動',['oneToOnes','referrals','referralAmount']],['會員經營',['firstYearRetention','retention','training']]];
    const grouped=values=>`<div class="kpi-groups">${groups.map(([title,ids])=>`<section class="kpi-group" aria-label="${title}"><h3>${title}</h3><dl>${ids.map(id=>{const f=M.fields.find(f=>f.id===id);return `<div data-kpi-metric="${id}"><dt>${E(f.label)}</dt><dd><strong>${M.display(values[id])}</strong><span>${f.unit}</span></dd></div>`;}).join('')}</dl></section>`).join('')}</div>`;
    function render(){const t=M.current(getData()),values=t?.values||M.empty();panel.innerHTML=`<div class="kpi-head"><div><span class="kpi-term">第11屆 · 2026/10–2027/9</span><h2>本屆 KPI 目標</h2></div><button type="button" class="secondary small-button" data-kpi-edit>設定目標</button></div>${grouped(values)}<div class="kpi-foot"><span>— 尚未設定 · 以上為目標值</span>${t?`<button type="button" class="text-button" data-kpi-history>修改紀錄 · ${t.history.length}</button>`:''}</div>`;panel.querySelector('[data-kpi-edit]').onclick=()=>open();panel.querySelector('[data-kpi-history]')?.addEventListener('click',()=>open(true));}
    const dirty=()=>!!state?.dirty;
    function leave(){if(!dialog.open)return true;if(dirty()&&!confirm('本屆 KPI 尚未儲存，要放棄這次修改嗎？'))return false;dialog.close();state=null;return true;}
    function open(history=false){const t=M.current(getData());state={revision:getData().revision,dirty:false};const values=t?.values||M.empty();dialog.innerHTML=`<header class="dialog-head"><div><small>第11屆 · 2026/10–2027/9</small><h2 id="termKpiTitle">本屆 KPI 設定</h2></div><button type="button" class="icon-button" data-kpi-close aria-label="關閉 KPI 設定">×</button></header><form id="termKpiForm" novalidate><p class="muted tiny">填寫共識後的目標，尚未決定的項目可以留空。</p><div class="kpi-inputs">${M.fields.map(f=>`<label>${f.label}<span><input name="${f.id}" inputmode="${f.kind==='count'?'numeric':'decimal'}" maxlength="18" value="${values[f.id]??''}" placeholder="尚未設定" autocomplete="off" aria-label="${f.label}" aria-describedby="termKpiRules"><b>${f.unit}</b></span></label>`).join('')}</div><p class="muted tiny" id="termKpiRules">人數、次數及單數填整數；百分比為 0–100，百分比與金額可填兩位小數。</p><p class="error" id="termKpiError" role="alert"></p><details class="kpi-history" ${history?'open':''}><summary>修改紀錄${t?' · '+t.history.length:''}</summary>${t?.history.length?`<label>查看保存版本<select id="termKpiVersion">${t.history.map((h,i)=>`<option value="${i}" ${i===t.history.length-1?'selected':''}>${E(stamp(h.at))} · ${E(h.by)} · 第 ${i+1} 次</option>`).reverse().join('')}</select></label><div id="termKpiSnapshot">${metrics(t.history.at(-1).values,'kpi-history-grid')}</div>`:'<p>尚無保存紀錄</p>'}</details><footer class="kpi-actions"><span>儲存後更新首頁</span><button type="button" class="secondary" data-kpi-close>取消</button><button type="submit" class="primary">儲存目標</button></footer></form>`;
      dialog.querySelectorAll('[data-kpi-close]').forEach(b=>b.onclick=leave);
      dialog.querySelector('form').oninput=e=>{if(e.target.name)state.dirty=true;};
      const select=dialog.querySelector('#termKpiVersion');if(select)select.onchange=()=>dialog.querySelector('#termKpiSnapshot').innerHTML=metrics(t.history[Number(select.value)].values,'kpi-history-grid');
      dialog.querySelector('form').onsubmit=e=>{e.preventDefault();try{const values=M.parse(Object.fromEntries(new FormData(e.target)));if(!dirty()){leave();return;}commit(d=>M.apply(d,values,identity.identity),state.revision);state.dirty=false;leave();toast('本屆 KPI 目標已儲存');}catch(err){dialog.querySelector('#termKpiError').textContent=err.message;}};
      dialog.showModal();if(history)dialog.querySelector('.kpi-history').scrollIntoView({block:'nearest'});
    }
    dialog.addEventListener('cancel',e=>{e.preventDefault();leave();});dialog.addEventListener('close',()=>{state=null;panel.querySelector('[data-kpi-edit]')?.focus({preventScroll:true});});
    function storageChanged(){if(dialog.open)dialog.querySelector('#termKpiError').textContent='另一分頁更新了資料，輸入已保留。請先複製未存內容，再關閉重開核對。';}
    return {render,dirty,leave,storageChanged};
  }};
})();
